### ISSUE TITLE
Fix licensing and copyright

### ISSUE THREAD

**Issue by crawfxrd** [GalileiOS/GalileiOS#1]
You are free to fork ReactOS if you want. However, you must do it a legal manner.

* ReactOS is licensed under the GPL. As such, you cannot license your fork under the MIT license.
* You are blatantly violating copyright by removing original copyright notices and adding your own.

**Comment by nicoalta01** [comment]
Ok.. I will Fix it tonight. Thank you To report issue. 0.4 will be on 25th december

**Comment by nicoalta01** [comment]
Is It ok now?

**Comment by crawfxrd** [comment]
No. At the very least, you still need to revert 511a320 and 63f0437, and add a copy of the other licenses used in the top level.

**Comment by nicoalta01** [comment]
Now?

**Comment by nicoalta01** [comment]
?

**Comment by nicoalta01** [comment]
Crawfxrd is It ok now?
