### ISSUE TITLE
GalileiOS Store dont work

### ISSUE THREAD

**Issue by tartaglia** [GalileiOS/GalileiOS#2]
Hi. i download GalileiOS 0.4 and it wonts work. i click on a catagory and i donts see anything come up.

**Comment by nicoalta01** [comment]
@tartaglia Have You got internet connection? Does it work?

**Comment by nicoalta01** [comment]
Check your internet connection

**Comment by tartaglia** [comment]
@nicoalta01 My internet works good. I can access sites good.

**Comment by nicoalta01** [comment]
Ok... on GalileiOs too?

**Comment by tartaglia** [comment]
Yes. The internet works good.

**Comment by nicoalta01** [comment]
Ok. .. The empty rapps is normally... On livecd You haven t got permessions of write iso.. When I will relase BootCD, I  open The issue. Thank You And bye. Ps: There will be a BootCD on january 2016..

**Comment by nicoalta01** [comment]
No. This must be open.

**Comment by nicoalta01** [comment]
@tartaglia You haven't got permessions of write the ISO (Livecd). For this, The store doesn't download the list of Apps...

**Comment by nicoalta01** [comment]
THE STORE WORKS but it's only Bootcd Test
![0033](https://cloud.githubusercontent.com/assets/8680441/12024057/8f464f14-ada0-11e5-83e6-05c402c9b5e0.png)

**Comment by tartaglia** [comment]
ok. i will wait.

**Comment by nicoalta01** [comment]
Close as fixed...

**Comment by nicoalta01** [comment]
@tartaglia https://github.com/GalileiOS/GalileiOS/releases/tag/0.4.1-alpha
please download bootcd
